### ISSUE TITLE
Make a Home Page. (100 pts)

### ISSUE THREAD

**Issue by Rosterz** [ucsb-cs56-f18/ucsb-cs56-qa#10]
Make a homepage where all users are taken to upon login/account registry. On the user's homepage list the user's 4 most recent questions and include their corresponding top answer. Also have the users profile portrayed on the homepage with total points below it and with a list of contributions as well.

**Comment by ryantse** [comment]
Mentor approved (100 points).

**Comment by TgWang1023** [comment]
Version 1 Complete

**Comment by TgWang1023** [comment]
Pull request submitted. Name: "Login Page and Home Page".
