### ISSUE TITLE
Add Github Authentication

### ISSUE THREAD

**Issue by ChangweiXu** [ucsb-cs56-f18/ucsb-cs56-qa#12]
We will be using Github for authentication. This will be used mainly for security reasons so that only people from the ucsb-cs56-f18 org have access to the website functionality. If users try to go to web pages without authenticating they will be given an unauthorized error.

**Comment by Rosterz** [comment]
We are using Github authentication so that only users from the cs56 organization can view the contents of our website. This will be our method for security for now.
