### ISSUE TITLE
Design a question page where users can view answers and create new answers to a single question. (150 pts)

### ISSUE THREAD

**Issue by ChangweiXu** [ucsb-cs56-f18/ucsb-cs56-qa#2]
On this page, users can view a question detail and all answers to it. They can also compose new answer regarding the question. Once created, the page refreshes and the new answer is append to the answers' list.

[Pull Request #4](https://github.com/ucsb-cs56-webapps/ucsb-cs56-qa/pull/4)

**Comment by ryantse** [comment]
Mentor Approved (150 pts).
