### ISSUE TITLE
Create a new question page (100 pts)

### ISSUE THREAD

**Issue by jxu495** [ucsb-cs56-f18/ucsb-cs56-qa#3]
On this page, users can ask a new question. The submission should have a main question and optionally include details to elaborate on the question.
-- special thanks to Ryan who give this awesome description --

[Pull Request #4](https://github.com/ucsb-cs56-webapps/ucsb-cs56-qa/pull/4)

**Comment by ryantse** [comment]
Mentor Approved (100 pts).
