### ISSUE TITLE
Database (400 pts)

### ISSUE THREAD

**Issue by jxu495** [ucsb-cs56-f18/ucsb-cs56-qa#4]
* Create a Firebase DB and link it to our website so that submitted questions are stored in Firebase DB and retrieved from Firebase DB.

* Along with a database for all user submitted questions, also create a Authentication Firebase DB so that we can store user's accounts.

[Pull Request #4](https://github.com/ucsb-cs56-webapps/ucsb-cs56-qa/pull/4)

**Comment by ryantse** [comment]
You may want to expand on this a little more. What is involved in storing something in a database? (i.e. potentially include a checklist of steps such as: "creating a Firebase DB", "designing the schema", etc.)

**Comment by Rosterz** [comment]
Along with a database for all user submitted questions, also create a Authentication Firebase DB so that we can store user's accounts.

**Comment by ryantse** [comment]
Mentor approved (400 pts).

**Comment by jxu495** [comment]
Pull Request Submitted: [https://github.com/ucsb-cs56-webapps/ucsb-cs56-qa/pull/3](url)
Pull Request number 3.
