### ISSUE TITLE
Create basic Spring Boot Webapp Template for app (100 pts)

### ISSUE THREAD

**Issue by jxu495** [ucsb-cs56-f18/ucsb-cs56-qa#5]
Create a basic Spring Boot webapp with Bootstrap navigation with tabs for Main Page, Questions Page, and Q&A Page.

**Comment by ryantse** [comment]
Mentor Approved (100 pts).

**Comment by jxu495** [comment]
Pull request submitted. Name: "Login Page and Home Page".
[https://github.com/ucsb-cs56-webapps/ucsb-cs56-qa/pull/2]
