### ISSUE TITLE
Make the user profile page. (200 pts)

### ISSUE THREAD

**Issue by ChangweiXu** [ucsb-cs56-f18/ucsb-cs56-qa#6]
Since users need to view their profiles or even modify details, this page can allows them to do those work.

[Pull Request #4](https://github.com/ucsb-cs56-webapps/ucsb-cs56-qa/pull/4)

**Comment by ryantse** [comment]
Mentor Approved (200 pts).

**Comment by jxu495** [comment]
Pull Request Submitted: [https://github.com/ucsb-cs56-webapps/ucsb-cs56-qa/pull/5](url)
Pull Request number 5.
