### ISSUE TITLE
Make a login page (100 pts)

### ISSUE THREAD

**Issue by Rosterz** [ucsb-cs56-f18/ucsb-cs56-qa#8]
Construct a login page where users submit their email/username and password. Then check to see if their account is on our authentication Firebase database. If their account is found then allow user to login with their associated information and sent to home page. If account is not found, then notify the user that their account is not found.
* Make sure users can't bypass login by typing /index

**Comment by ryantse** [comment]
Mentor approved (100 points).

**Comment by TgWang1023** [comment]
Done with version 1, not responsive

**Comment by TgWang1023** [comment]
Pull request submitted. Name: "Login Page and Home Page".
