### ISSUE TITLE
Make a Account Registry Page (150 pts)

### ISSUE THREAD

**Issue by Rosterz** [ucsb-cs56-f18/ucsb-cs56-qa#9]
Make a page where users can submit a username/email and password so that they can make a account with the corresponding details. Check to see if user password is appropriate (long enough) 

* then check to see if there exists an account with the user submitted details. If the account already exists in the Authentication Firebase DB then notify user that "a account with that email already exists". If the account does not exists yet, then create the new account by adding it to our Authentication Firebase Database. Once created send user to the webapp homepage.

[Pull Request #4](https://github.com/ucsb-cs56-webapps/ucsb-cs56-qa/pull/4)

**Comment by ryantse** [comment]
Mentor approved (150 points).

**Comment by ryantse** [comment]
No error is currently returned when the user already exists.

**Comment by jxu495** [comment]
Pull Request Submitted: [https://github.com/ucsb-cs56-webapps/ucsb-cs56-qa/pull/6](url)
Pull Request number 6.
